### ISSUE TITLE
wpn_scar_siber_m2_custom black box in scope

### ISSUE THREAD

**Issue by Hoshizoku** [andtheherois/3DSS-Re-Enabled-Guns#1]
Black box in scope, kinda works without reenabled gun lol

https://discord.com/channels/912320241713958912/1219433143069708299/1259950138458374298

![grafik](https://github.com/andtheherois/3DSS-Re-Enabled-Guns/assets/174358400/9f9a9d7f-2535-4ede-87a7-a8798cb89ed6)

**Comment by andtheherois** [comment]
fixed
